"""restructure models to English naming

Revision ID: 305f4275bafa
Revises: 58f954bb8ff7
Create Date: 2026-09-21 22:37:03.682301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '305f4275bafa'
down_revision: Union[str, Sequence[str], None] = '58f954bb8ff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('content_full', sa.Text(), nullable=False),
    sa.Column('summary', sa.String(length=2000), nullable=True),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('telegram_message_id', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_message_id')
    )
    op.drop_table('envios')
    op.drop_table('noticias')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('envios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('noticia_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('telegram_message_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sucesso', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['noticia_id'], ['noticias.id'], name=op.f('envios_noticia_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('envios_pkey')),
    sa.UniqueConstraint('telegram_message_id', name=op.f('envios_telegram_message_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('noticias',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url', sa.VARCHAR(length=2048), autoincrement=False, nullable=False),
    sa.Column('resumo', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('feed_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], name=op.f('noticias_feed_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('noticias_pkey')),
    sa.UniqueConstraint('url', name=op.f('noticias_url_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('deliveries')
    op.drop_table('articles')
    # ### end Alembic commands ###
